var = input('Type something: ')
print(f'The value type is {type(var)}')
print(f'Is only space: {var.isspace()}')
print(f'Is numeric: {var.isnumeric()}')
print(f'Is alfabetic: {var.isalpha()}')
print(f'Is alfanumeric: {var.isalnum()}')
print(f'Is uppercase: {var.isupper()}')
print(f'Is lowercase: {var.islower()}')
print(f'Is capitalized: {var.istitle()}')